# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: nginx

replicaCount: 1

image:
  repository: nginx
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"